#!/usr/bin/env node
/*
 * Builds the files the page loads instead of CDNs, so the book opens fast on
 * phones and works offline. Run it after adding Tailwind classes or icons:
 *
 *   npm install        (once)
 *   npm run build
 *
 * It writes (all committed, so the site itself needs no build step):
 *  - css/tailwind.css            the Tailwind classes used in index.html and js/
 *  - css/icons.css, fonts/icons.woff2
 *                                only the Font Awesome icons the code uses
 *  - css/fonts.css, fonts/*.woff2
 *                                Fredoka (Latin) and Nunito (Latin + Cyrillic)
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const FA = path.join(NM, '@fortawesome/fontawesome-free');
const FONTS = [
    { family: 'Fredoka', pkg: '@fontsource-variable/fredoka', subsets: ['latin-ext', 'latin'] },
    { family: 'Nunito', pkg: '@fontsource-variable/nunito', subsets: ['cyrillic-ext', 'cyrillic', 'latin-ext', 'latin'] },
];

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, data) => {
    fs.mkdirSync(path.dirname(path.join(ROOT, p)), { recursive: true });
    fs.writeFileSync(path.join(ROOT, p), data);
    console.log(`  wrote ${p}`);
};

// ---------- Tailwind ----------

function tailwind(out = 'css/tailwind.css') {
    execFileSync(path.join(NM, '.bin', 'tailwindcss'), ['-c', 'tailwind.config.js', '-i', 'css/tailwind.src.css', '-o', out, '--minify'], { cwd: ROOT, stdio: 'pipe' });
    return out;
}

// ---------- icons ----------

// Icon names in class lists: "fa-solid fa-book-open" -> book-open.
function usedIcons() {
    const files = ['index.html', ...fs.readdirSync(path.join(ROOT, 'js')).filter((f) => f.endsWith('.js')).map((f) => `js/${f}`)];
    const names = new Set();
    files.forEach((f) => {
        for (const m of read(f).matchAll(/\bfa-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) names.add(m[1]);
    });
    ['solid', 'regular', 'brands', 'classic', 'sharp'].forEach((style) => names.delete(style));
    return [...names].sort();
}

// name -> code point, from Font Awesome's own stylesheet.
function iconCodes() {
    const css = fs.readFileSync(path.join(FA, 'css/all.css'), 'utf8');
    const codes = {};
    for (const m of css.matchAll(/((?:\.fa-[a-z0-9-]+::before\s*,?\s*)+)\{\s*content:\s*"\\([0-9a-f]+)"/g)) {
        for (const s of m[1].matchAll(/\.fa-([a-z0-9-]+)::before/g)) codes[s[1]] = m[2];
    }
    return codes;
}

async function icons() {
    const subsetFont = require('subset-font');
    const names = usedIcons();
    const codes = iconCodes();
    const unknown = names.filter((n) => !codes[n]);
    if (unknown.length) throw new Error(`not Font Awesome Free icons: ${unknown.join(', ')}`);
    const text = names.map((n) => String.fromCodePoint(parseInt(codes[n], 16))).join('');
    const ttf = fs.readFileSync(path.join(FA, 'webfonts/fa-solid-900.ttf'));
    write('fonts/icons.woff2', await subsetFont(ttf, text, { targetFormat: 'woff2' }));
    write('css/icons.css', `/*
 * Generated by tools/build-assets.js: the ${names.length} Font Awesome Free (solid) icons
 * this app uses. Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
 * Icons: CC BY 4.0, font: SIL OFL 1.1 (see fonts/LICENSE-fontawesome.txt).
 */
@font-face {
    font-family: 'Font Awesome 6 Free';
    font-style: normal;
    font-weight: 900;
    font-display: block;
    src: url(../fonts/icons.woff2) format('woff2');
}

.fa-solid {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    display: var(--fa-display, inline-block);
    font-family: 'Font Awesome 6 Free';
    font-style: normal;
    font-variant: normal;
    font-weight: 900;
    line-height: 1;
    text-rendering: auto;
}

${names.map((n) => `.fa-${n}::before { content: "\\${codes[n]}"; }`).join('\n')}
`);
    fs.copyFileSync(path.join(FA, 'LICENSE.txt'), path.join(ROOT, 'fonts/LICENSE-fontawesome.txt'));
}

// ---------- fonts ----------

function fonts() {
    const faces = [];
    FONTS.forEach(({ family, pkg, subsets }) => {
        const dir = path.join(NM, pkg);
        const css = fs.readFileSync(path.join(dir, 'wght.css'), 'utf8');
        subsets.forEach((subset) => {
            const block = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]*)\}/g)].find((m) => m[1].endsWith(`-${subset}-wght-normal`));
            if (!block) throw new Error(`${pkg}: no ${subset} subset`);
            const file = block[2].match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
            const weight = block[2].match(/font-weight: ([^;]+);/)[1];
            const range = block[2].match(/unicode-range: ([^;]+);/)[1];
            fs.copyFileSync(path.join(dir, 'files', file), path.join(ROOT, 'fonts', file));
            faces.push(`/* ${family} ${subset} */
@font-face {
    font-family: '${family}';
    font-style: normal;
    font-display: swap;
    font-weight: ${weight};
    src: url(../fonts/${file}) format('woff2');
    unicode-range: ${range};
}`);
        });
        fs.copyFileSync(path.join(dir, 'LICENSE'), path.join(ROOT, `fonts/LICENSE-${family.toLowerCase()}.txt`));
    });
    write('css/fonts.css', `/*
 * Generated by tools/build-assets.js from Fontsource: Fredoka (headings) and
 * Nunito (text). SIL Open Font License 1.1 (see fonts/LICENSE-*.txt).
 * Fredoka has no Cyrillic letters; the stacks in the CSS fall back to Nunito.
 */
${faces.join('\n\n')}
`);
}

module.exports = { tailwind, usedIcons };

if (require.main === module) {
    (async () => {
        fs.mkdirSync(path.join(ROOT, 'fonts'), { recursive: true });
        console.log('Tailwind');
        tailwind();
        console.log('  wrote css/tailwind.css');
        console.log('Icons');
        await icons();
        console.log('Fonts');
        fonts();
    })().catch((e) => {
        console.error(`✗ ${e.message}`);
        process.exit(1);
    });
}
