#!/usr/bin/env node
/*
 * Builds the files the page loads instead of CDNs, so the book opens fast on
 * phones and works offline. Run it after adding Tailwind classes or icons:
 *
 *   npm install        (once)
 *   npm run build
 *
 * It writes (all committed, so the site itself needs no build step):
 *  - css/tailwind.css            the Tailwind classes used in index.html and js/
 *  - css/icons.css, fonts/icons.woff2
 *                                only the Font Awesome icons the code uses
 *  - css/fonts.css, fonts/*.woff2
 *                                Fredoka (Latin), Nunito (Latin + Cyrillic) and
 *                                Gowun Dodum (only the Korean letters the app uses)
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const FA = path.join(NM, '@fortawesome/fontawesome-free');
const FONTS = [
    { family: 'Fredoka', pkg: '@fontsource-variable/fredoka', subsets: ['latin-ext', 'latin'] },
    { family: 'Nunito', pkg: '@fontsource-variable/nunito', subsets: ['cyrillic-ext', 'cyrillic', 'latin-ext', 'latin'] },
];
const KOREAN = path.join(NM, '@expo-google-fonts/gowun-dodum');
const HANGUL = /[\u1100-\u11ff\u3130-\u318f\uac00-\ud7a3]/g;

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, data) => {
    fs.mkdirSync(path.dirname(path.join(ROOT, p)), { recursive: true });
    fs.writeFileSync(path.join(ROOT, p), data);
    console.log(`  wrote ${p}`);
};

// ---------- Tailwind ----------

function tailwind(out = 'css/tailwind.css') {
    execFileSync(path.join(NM, '.bin', 'tailwindcss'), ['-c', 'tailwind.config.js', '-i', 'css/tailwind.src.css', '-o', out, '--minify'], { cwd: ROOT, stdio: 'pipe' });
    return out;
}

// ---------- icons ----------

// Icon names in class lists: "fa-solid fa-book-open" -> book-open.
function usedIcons() {
    const files = ['index.html', ...fs.readdirSync(path.join(ROOT, 'js')).filter((f) => f.endsWith('.js')).map((f) => `js/${f}`)];
    const names = new Set();
    files.forEach((f) => {
        for (const m of read(f).matchAll(/\bfa-([a-z0-9]+(?:-[a-z0-9]+)*)/g)) names.add(m[1]);
    });
    ['solid', 'regular', 'brands', 'classic', 'sharp'].forEach((style) => names.delete(style));
    return [...names].sort();
}

// name -> code point, from Font Awesome's own stylesheet.
function iconCodes() {
    const css = fs.readFileSync(path.join(FA, 'css/all.css'), 'utf8');
    const codes = {};
    for (const m of css.matchAll(/((?:\.fa-[a-z0-9-]+::before\s*,?\s*)+)\{\s*content:\s*"\\([0-9a-f]+)"/g)) {
        for (const s of m[1].matchAll(/\.fa-([a-z0-9-]+)::before/g)) codes[s[1]] = m[2];
    }
    return codes;
}

async function icons() {
    const subsetFont = require('subset-font');
    const names = usedIcons();
    const codes = iconCodes();
    const unknown = names.filter((n) => !codes[n]);
    if (unknown.length) throw new Error(`not Font Awesome Free icons: ${unknown.join(', ')}`);
    const text = names.map((n) => String.fromCodePoint(parseInt(codes[n], 16))).join('');
    const ttf = fs.readFileSync(path.join(FA, 'webfonts/fa-solid-900.ttf'));
    write('fonts/icons.woff2', await subsetFont(ttf, text, { targetFormat: 'woff2' }));
    write('css/icons.css', `/*
 * Generated by tools/build-assets.js: the ${names.length} Font Awesome Free (solid) icons
 * this app uses. Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
 * Icons: CC BY 4.0, font: SIL OFL 1.1 (see fonts/LICENSE-fontawesome.txt).
 */
@font-face {
    font-family: 'Font Awesome 6 Free';
    font-style: normal;
    font-weight: 900;
    font-display: block;
    src: url(../fonts/icons.woff2) format('woff2');
}

.fa-solid {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    display: var(--fa-display, inline-block);
    font-family: 'Font Awesome 6 Free';
    font-style: normal;
    font-variant: normal;
    font-weight: 900;
    line-height: 1;
    text-rendering: auto;
}

${names.map((n) => `.fa-${n}::before { content: "\\${codes[n]}"; }`).join('\n')}
`);
    fs.copyFileSync(path.join(FA, 'LICENSE.txt'), path.join(ROOT, 'fonts/LICENSE-fontawesome.txt'));
}

// ---------- fonts ----------

// Every Hangul letter the page can show: the menus (js/i18n.js), the Korean
// helper (js/stories-ko.js) and the few Korean words elsewhere. Not the 가
// readings (js/hangul.js): they can be any syllable, so they use the phone's font.
function hangulUsed() {
    const files = ['index.html'];
    const walk = (dir) => fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).forEach((d) => {
        if (d.isDirectory()) walk(`${dir}/${d.name}`);
        // js/hangul.js makes readings that use the phone's own Korean font (.read-line)
        else if (d.name.endsWith('.js') && `${dir}/${d.name}` !== 'js/hangul.js') files.push(`${dir}/${d.name}`);
    });
    walk('js');
    const chars = new Set();
    files.forEach((f) => {
        for (const [c] of read(f).matchAll(HANGUL)) chars.add(c);
    });
    return [...chars].sort().join('');
}

// A whole Korean font is megabytes; the app needs a few hundred letters.
// fonts/gowun-dodum-ko.txt lists them, so a test can tell when new Korean
// text needs a rebuild.
async function korean() {
    const subsetFont = require('subset-font');
    const text = hangulUsed();
    const ttf = fs.readFileSync(path.join(KOREAN, '400Regular/GowunDodum_400Regular.ttf'));
    write('fonts/gowun-dodum-ko.woff2', await subsetFont(ttf, text, { targetFormat: 'woff2' }));
    write('fonts/gowun-dodum-ko.txt', `${text}\n`);
    fs.copyFileSync(path.join(KOREAN, 'LICENSE_FONT'), path.join(ROOT, 'fonts/LICENSE-gowun-dodum.txt'));
    return `/* Gowun Dodum korean: ${text.length} letters (fonts/gowun-dodum-ko.txt) */
@font-face {
    font-family: 'Gowun Dodum';
    font-style: normal;
    font-display: swap;
    font-weight: 400;
    src: url(../fonts/gowun-dodum-ko.woff2) format('woff2');
    unicode-range: U+1100-11FF,U+3130-318F,U+AC00-D7A3;
}`;
}

async function fonts() {
    const faces = [];
    FONTS.forEach(({ family, pkg, subsets }) => {
        const dir = path.join(NM, pkg);
        const css = fs.readFileSync(path.join(dir, 'wght.css'), 'utf8');
        subsets.forEach((subset) => {
            const block = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]*)\}/g)].find((m) => m[1].endsWith(`-${subset}-wght-normal`));
            if (!block) throw new Error(`${pkg}: no ${subset} subset`);
            const file = block[2].match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
            const weight = block[2].match(/font-weight: ([^;]+);/)[1];
            const range = block[2].match(/unicode-range: ([^;]+);/)[1];
            fs.copyFileSync(path.join(dir, 'files', file), path.join(ROOT, 'fonts', file));
            faces.push(`/* ${family} ${subset} */
@font-face {
    font-family: '${family}';
    font-style: normal;
    font-display: swap;
    font-weight: ${weight};
    src: url(../fonts/${file}) format('woff2');
    unicode-range: ${range};
}`);
        });
        fs.copyFileSync(path.join(dir, 'LICENSE'), path.join(ROOT, `fonts/LICENSE-${family.toLowerCase()}.txt`));
    });
    faces.push(await korean());
    write('css/fonts.css', `/*
 * Generated by tools/build-assets.js: Fredoka (headings) and Nunito (text) from
 * Fontsource, Gowun Dodum (Korean) from Google Fonts. SIL Open Font License 1.1
 * (see fonts/LICENSE-*.txt). Fredoka has no Cyrillic letters and neither has
 * Korean ones; the stacks in the CSS fall back to Nunito, then Gowun Dodum.
 */
${faces.join('\n\n')}
`);
}

module.exports = { tailwind, usedIcons, hangulUsed };

if (require.main === module) {
    (async () => {
        fs.mkdirSync(path.join(ROOT, 'fonts'), { recursive: true });
        console.log('Tailwind');
        tailwind();
        console.log('  wrote css/tailwind.css');
        console.log('Icons');
        await icons();
        console.log('Fonts');
        await fonts();
    })().catch((e) => {
        console.error(`✗ ${e.message}`);
        process.exit(1);
    });
}
